'use strict'

const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const indexSource = fs.readFileSync(path.join(__dirname, 'index.js'), 'utf8')
const adminServiceSource = fs.readFileSync(path.join(__dirname, 'user-membership-admin-service.js'), 'utf8')

test('预授权领取只挂在微信可信手机号链路且没有公开 claim action', () => {
  assert.match(indexSource, /cloud\.openapi\.phonenumber\.getPhoneNumber\(\{ code \}\)/)
  assert.match(indexSource, /bindPhoneInternal\(phone, event, wxContext\)/)
  assert.match(indexSource, /resolvePendingPreauthorizationInTransaction/)
  assert.doesNotMatch(indexSource, /case\s+['"]claimPendingEntitlement['"]/)
  assert.doesNotMatch(indexSource, /case\s+['"]claimPreRegistrationEntitlement['"]/)
})

test('领取审计和显式四态均保留，日志只保存脱敏手机号', () => {
  const auditStart = indexSource.indexOf("action: 'PREAUTH_CLAIM'")
  const claimAuditSource = indexSource.slice(auditStart, auditStart + 2200)
  assert.ok(auditStart >= 0)
  assert.match(claimAuditSource, /targetPhoneMasked:\s*maskPhone\(phone\)/)
  assert.doesNotMatch(claimAuditSource, /targetPhone:\s*phone[\s,}]/)
})

test('会员鉴权只使用服务端已绑定手机号，忽略客户端传入的其他手机号', () => {
  const accessStart = indexSource.indexOf('async function getCurrentAccess')
  const accessSource = indexSource.slice(accessStart, accessStart + 1800)
  assert.ok(accessStart >= 0)
  assert.match(accessSource, /resolveTrustedBoundPhone\(user \|\| \{\}\)/)
  assert.match(accessSource, /phone = trustedPhone/)
  assert.doesNotMatch(accessSource, /phone = user\.phone/)
})

test('手机号绑定事务完成后再次 reconciliation，关闭管理员创建并发窗口', () => {
  const bindStart = indexSource.indexOf('async function bindPhoneInternal')
  const bindSource = indexSource.slice(bindStart, bindStart + 2600)
  assert.ok(bindStart >= 0)
  assert.match(bindSource, /upsertPhoneAuthenticatedUser\(openid, phone, membershipProfile\)/)
  assert.match(bindSource, /reconcileBoundPhoneUser\(nextUser\._id, phone\)/)
})

test('预登记权益协调失败不会回滚已完成的手机号登录主链路', () => {
  const upsertStart = indexSource.indexOf('async function upsertPhoneAuthenticatedUser')
  const upsertEnd = indexSource.indexOf('async function reconcileBoundPhoneUser')
  const upsertSource = indexSource.slice(upsertStart, upsertEnd)
  const bindStart = indexSource.indexOf('async function bindPhoneInternal')
  const bindSource = indexSource.slice(bindStart, bindStart + 3600)
  assert.doesNotMatch(upsertSource, /resolvePendingPreauthorizationInTransaction/)
  assert.match(bindSource, /try\s*{[\s\S]*reconcileBoundPhoneUser\(nextUser\._id, phone\)[\s\S]*}\s*catch/)
  assert.match(bindSource, /phone login entitlement reconciliation deferred/)
})

test('未领取的预登记权益不会作为普通手机号权益提前生效', () => {
  const entitlementStart = indexSource.indexOf('async function getPhoneEntitlement')
  const entitlementEnd = indexSource.indexOf('async function listPhoneEntitlements')
  const entitlementSource = indexSource.slice(entitlementStart, entitlementEnd)
  assert.match(entitlementSource, /filter\(isDirectPhoneEntitlement\)/)
})

test('普通手机号无预授权时不会读取不存在的确定性文档并中断绑定', () => {
  const resolveStart = indexSource.indexOf('async function resolvePendingPreauthorizationInTransaction')
  const resolveEnd = indexSource.indexOf('async function upsertPhoneAuthenticatedUser')
  const resolveSource = indexSource.slice(resolveStart, resolveEnd)
  assert.ok(resolveStart >= 0 && resolveEnd > resolveStart)
  assert.doesNotMatch(resolveSource, /doc\(deterministicId\)\.get\(\)/)
  assert.match(resolveSource, /_id:\s*deterministicId/)
  assert.match(resolveSource, /historyArchive !== true/)
  assert.match(resolveSource, /where\(_\.and/)
})

test('可信手机号不允许在普通绑定链路中直接换绑并复制旧权益', () => {
  const upsertStart = indexSource.indexOf('async function upsertPhoneAuthenticatedUser')
  const upsertEnd = indexSource.indexOf('async function reconcileBoundPhoneUser')
  const upsertSource = indexSource.slice(upsertStart, upsertEnd)
  assert.ok(upsertStart >= 0 && upsertEnd > upsertStart)
  assert.match(upsertSource, /PHONE_REBIND_NOT_ALLOWED/)
  assert.match(upsertSource, /phoneNormalized/)
  assert.match(upsertSource, /readPhoneBindingLockInTransaction/)
  assert.match(upsertSource, /persistPhoneBindingLockInTransaction/)
})

test('预授权编辑禁止改手机号，避免确定性文档 ID 被复用覆盖', () => {
  assert.match(adminServiceSource, /PREAUTH_PHONE_CHANGE_NOT_ALLOWED/)
  assert.match(adminServiceSource, /撤销后重新创建/)
  assert.match(adminServiceSource, /const deterministicId = getPreauthorizationDocumentId\(normalized\.phone\)/)
  assert.match(adminServiceSource, /historyArchive !== true/)
})

test('已注册手机号识别兼容缺少 phoneBound 的历史 users', () => {
  const lookupStart = adminServiceSource.indexOf('async function getRegisteredUserByPhone')
  const lookupSource = adminServiceSource.slice(lookupStart, lookupStart + 500)
  assert.ok(lookupStart >= 0)
  assert.match(lookupSource, /phoneNormalized/)
  assert.doesNotMatch(lookupSource, /phoneBound/)
})

test('管理员创建预授权只写 entitlement 和 audit，不伪造 users', () => {
  const saveStart = adminServiceSource.indexOf('async function adminSavePreRegistrationEntitlement')
  const saveEnd = adminServiceSource.indexOf('async function adminRevokePreRegistrationEntitlement')
  const saveSource = adminServiceSource.slice(saveStart, saveEnd)
  assert.ok(saveStart >= 0 && saveEnd > saveStart)
  assert.doesNotMatch(saveSource, /users\.add\s*\(/)
  assert.doesNotMatch(saveSource, /users\.doc\([^)]*\)\.set\s*\(/)
  assert.match(saveSource, /entitlements\.doc\(documentId\)\.set/)
  assert.match(saveSource, /auditLogs\.add/)
})

test('预注册收益只绑定创建操作，后续领取不会重复计入', () => {
  const saveStart = adminServiceSource.indexOf('async function adminSavePreRegistrationEntitlement')
  const saveEnd = adminServiceSource.indexOf('async function adminRevokePreRegistrationEntitlement')
  const saveSource = adminServiceSource.slice(saveStart, saveEnd)
  const claimStart = indexSource.indexOf("action: 'PREAUTH_CLAIM'")
  const claimSource = indexSource.slice(claimStart, claimStart + 2200)
  assert.match(saveSource, /auditAction === 'PREAUTH_CREATE'/)
  assert.match(saveSource, /revenueSource:\s*ADMIN_GRANT_REVENUE_SOURCE/)
  assert.match(saveSource, /auditLogs\.doc\(revenueAuditId\)\.set/)
  assert.doesNotMatch(claimSource, /revenueSource|revenueAmountFen|admin_grant/)
})

test('已注册用户人工发放以确定性 operationId 原子记录收益且不伪造支付订单', () => {
  const updateStart = adminServiceSource.indexOf('async function adminUpdateUserMembership')
  const updateEnd = adminServiceSource.indexOf('async function countManualActiveMembers')
  const updateSource = adminServiceSource.slice(updateStart, updateEnd)
  assert.match(updateSource, /getRevenueAuditDocumentId\(operationId\)/)
  assert.match(updateSource, /existingOperation/)
  assert.match(updateSource, /revenueAmountFen:\s*product\.priceFen/)
  assert.match(updateSource, /auditLogs\.doc\(revenueAuditId\)\.set/)
  assert.doesNotMatch(updateSource, /virtualPaymentOrders|transactionId|orderNo/)
})

test('支付履约在同一事务内校验可信手机号并原子更新订单、权益和用户', () => {
  const fulfillStart = indexSource.indexOf('async function fulfillMembershipOrder')
  const fulfillEnd = indexSource.indexOf('async function confirmVirtualPaymentOrder')
  const fulfillSource = indexSource.slice(fulfillStart, fulfillEnd)
  assert.ok(fulfillStart >= 0 && fulfillEnd > fulfillStart)
  assert.match(fulfillSource, /db\.runTransaction/)
  assert.match(fulfillSource, /PAYMENT_PHONE_BINDING_MISMATCH/)
  assert.match(fulfillSource, /latestPaymentOrderNo === currentOrder\.orderNo/)
  assert.match(fulfillSource, /users\.doc\(paymentUser\._id\)\.update/)
  assert.match(fulfillSource, /orders\.doc\(currentOrder\._id\)\.update/)
  assert.match(fulfillSource, /filter\(isDirectPhoneEntitlement\)/)
  assert.match(fulfillSource, /latestOrder\.status === 'fulfilled'/)
  assert.doesNotMatch(fulfillSource, /syncPhoneEntitlementUsers/)
})

test('后台人工会员调整使用事务内最新快照，避免覆盖并发支付结果', () => {
  const updateStart = adminServiceSource.indexOf('async function adminUpdateUserMembership')
  const updateEnd = adminServiceSource.indexOf('async function countManualActiveMembers')
  const updateSource = adminServiceSource.slice(updateStart, updateEnd)
  assert.ok(updateStart >= 0 && updateEnd > updateStart)
  assert.match(updateSource, /expectedMembership = membershipSnapshot\(user\)/)
  assert.match(updateSource, /membershipSnapshot\(currentUser\)/)
  assert.match(updateSource, /MEMBERSHIP_CHANGED_RETRY/)
  assert.match(updateSource, /db\.runTransaction/)
  assert.match(updateSource, /filter\(isDirectPhoneEntitlement\)/)
})

test('未来 fixed 领取会在用户文档保存待激活标记，成熟后再清除', () => {
  const metadataStart = indexSource.indexOf('function buildPreauthorizationUserMetadata')
  const metadataSource = indexSource.slice(metadataStart, metadataStart + 1600)
  const reconcileStart = indexSource.indexOf('async function reconcileBoundPhoneUser')
  const reconcileSource = indexSource.slice(reconcileStart, reconcileStart + 5200)
  assert.ok(metadataStart >= 0 && reconcileStart >= 0)
  assert.match(metadataSource, /preauthDeferred:\s*deferred/)
  assert.match(metadataSource, /preauthDeferredStartAt/)
  assert.match(metadataSource, /preauthDeferredEndAt/)
  assert.match(reconcileSource, /resolveMaturedDeferredPreauthorizationInTransaction/)
  assert.match(reconcileSource, /preauthDeferred:\s*false/)
  assert.match(reconcileSource, /expiredWithoutActivation/)
})

test('到期或遗留 pending 同步只由可信绑定用户、权限读取或管理员读取路径触发', () => {
  const accessStart = indexSource.indexOf('async function getCurrentAccess')
  const accessSource = indexSource.slice(accessStart, accessStart + 3200)
  const deferredStart = adminServiceSource.indexOf('async function reconcileMaturedDeferredUsers')
  const deferredEnd = adminServiceSource.indexOf('async function adminListUsers')
  const deferredSource = adminServiceSource.slice(deferredStart, deferredEnd)
  assert.match(accessSource, /shouldReconcilePreauthorization = user && trustedPhone/)
  assert.match(accessSource, /isDeferredPreauthorizationDue\(user\)/)
  assert.match(accessSource, /hasPendingPreauthorizationForPhone\(trustedPhone\)/)
  assert.match(accessSource, /reconcileBoundPhoneUser\(user\._id, trustedPhone\)/)
  assert.match(adminServiceSource, /async function reconcileMaturedDeferredUsers/)
  assert.match(adminServiceSource, /await reconcileMaturedDeferredUsers\(\)/)
  assert.match(adminServiceSource, /DEFERRED_RECONCILE_LIMIT = 20/)
  assert.doesNotMatch(deferredSource, /fetchAll/)
  assert.match(deferredSource, /preauthDeferredStartAt:\s*_\.lte\(dueAt\)/)
  assert.match(deferredSource, /orderBy\(['"]preauthDeferredStartAt['"],\s*['"]asc['"]\)/)
  assert.match(deferredSource, /limit\(DEFERRED_RECONCILE_LIMIT\)/)
  assert.doesNotMatch(indexSource, /case\s+['"]activateDeferredPreauthorization['"]/)
})

test('成熟同步区分有效与已过期 fixed 授权，不会补发已过期权益', () => {
  const resolveStart = indexSource.indexOf('async function resolveMaturedDeferredPreauthorizationInTransaction')
  const resolveEnd = indexSource.indexOf('async function readPhoneBindingLockInTransaction')
  const resolveSource = indexSource.slice(resolveStart, resolveEnd)
  assert.ok(resolveStart >= 0 && resolveEnd > resolveStart)
  assert.match(resolveSource, /classifyAdminMembership\(item, activationTimestamp\)\.isActiveMember/)
  assert.match(resolveSource, /membershipStatus:\s*'expired'/)
  assert.match(resolveSource, /activationSkippedAt/)
  assert.match(resolveSource, /expiredWithoutActivation:\s*matured\.length === 0/)
})

test('成熟同步后登录、getMe 与管理员编辑均使用最新用户快照', () => {
  const getMeStart = indexSource.indexOf('async function getMe')
  const getMeSource = indexSource.slice(getMeStart, getMeStart + 700)
  const bindStart = indexSource.indexOf('async function bindPhoneInternal')
  const bindSource = indexSource.slice(bindStart, bindStart + 3200)
  const updateStart = adminServiceSource.indexOf('async function adminUpdateUserMembership')
  const updateSource = adminServiceSource.slice(updateStart, updateStart + 1400)
  assert.match(getMeSource, /const effectiveUser = access\.user \|\| user/)
  assert.match(bindSource, /postTransactionReconciliation && postTransactionReconciliation\.user/)
  assert.match(updateSource, /reconciliation && reconciliation\.user/)
})
